# Generated by Django 6.0.1 on 2026-07-12 08:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('company', models.CharField(max_length=100, verbose_name='Компанія')),
                ('period', models.CharField(max_length=100, verbose_name='Період')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Досвід',
                'verbose_name_plural': 'Досвід',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Назва проєкту')),
                ('budget', models.PositiveIntegerField(verbose_name='Бюджет, USD')),
                ('deadline', models.DateField(verbose_name='Термін')),
                ('description', models.TextField(verbose_name='Опис замовлення')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Ім’я контакту')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email контакту')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон контакту')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('completed', 'Завершена'), ('cancelled', 'Скасована')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Ім’я клієнта')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компанія')),
                ('quote', models.TextField(verbose_name='Відгук')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекти'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', '-level'], 'verbose_name': 'Навичка', 'verbose_name_plural': 'Навички'},
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, help_text='Дата завершення проекту', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub посилання'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=200, verbose_name='Технології'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Фронтенд'), ('backend', 'Бекенд'), ('database', 'База даних'), ('devops', 'DevOps'), ('other', 'Інше')], max_length=50, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рівень'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
